class MeditationSvgAssets {
  static final MeditationSvgAssets _instance = MeditationSvgAssets._internal();

  factory MeditationSvgAssets() {
    return _instance;
  }

  MeditationSvgAssets._internal();

  Map<AssetName, String> assets = {
    AssetName.search: "assets/icons/search.svg",
    AssetName.vectorBottom: "assets/pics/Vector.svg",
    AssetName.vectorTop: "assets/pics/Vector-1.svg",
    AssetName.headphone: "assets/icons/headphone.svg",
    AssetName.tape: "assets/icons/tape.svg",
    AssetName.vectorSmallBottom: "assets/pics/VectorSmallBottom.svg",
    AssetName.vectorSmallTop: "assets/pics/VectorSmallTop.svg",
    AssetName.back: "assets/icons/back.svg",
    AssetName.heart: "assets/icons/heart.svg",
    AssetName.chart: "assets/icons/chart.svg",
    AssetName.discover: "assets/icons/discover.svg",
    AssetName.profile: "assets/icons/profile.svg",
    AssetName.aceOfSpades: "assets/icons/ace-of-spades-svgrepo-com ",
    AssetName.aceofspadessvgrepocom:'assets/icons/ace-of-spades-svgrepo-com.svg',
    AssetName.archerytargetsvgrepocom:'assets/icons/archery-target-svgrepo-com.svg',
    AssetName.audio:'assets/icons/audio-svgrepo-com.svg',
    AssetName.back1:'assets/icons/back.svg',
    AssetName.baseball1:'assets/icons/baseball-svgrepo-com.svg',
    AssetName.basketball:'assets/icons/basketball-svgrepo-com.svg',
    AssetName.bell:'assets/icons/bell-off-svgrepo-com.svg',
    AssetName.birthdaycupcake:'assets/icons/birthday-cupcake-svgrepo-com.svg',
    AssetName.bitcoin:'assets/icons/bitcoin-svgrepo-com.svg',
    AssetName.chart1:'assets/icons/chart.svg',
    AssetName.chessknight:'assets/icons/chess-knight-svgrepo-com.svg',
    AssetName.circledcheck:'assets/icons/circled-check-svgrepo-com.svg',
    AssetName.clap:'assets/icons/clap-svgrepo-com.svg',
    AssetName.codefile:'assets/icons/code-file-svgrepo-com.svg',
    AssetName.diamond:'assets/icons/diamond-svgrepo-com.svg',
    AssetName.dice:'assets/icons/dice-svgrepo-com.svg',
    AssetName.discover1:'assets/icons/discover.svg',
    AssetName.dribbble:'assets/icons/dribbble-svgrepo-com.svg',
    AssetName.electricguitar:'assets/icons/electric-guitar-svgrepo-com.svg',
    AssetName.exit:'assets/icons/exit-svgrepo-com.svg',
    AssetName.experiment:'assets/icons/experiment-svgrepo-com.svg',
    AssetName.filetext:'assets/icons/file-text-svgrepo-com.svg',
    AssetName.gamepad:'assets/icons/gamepad-svgrepo-com.svg',
    AssetName.gear:'assets/icons/gear-svgrepo-com.svg',
    AssetName.ghost:'assets/icons/ghost-svgrepo-com.svg',
    AssetName.headphone1:'assets/icons/headphone.svg',
    AssetName.heart1:'assets/icons/heart.svg',
    AssetName.house:'assets/icons/house-svgrepo-com.svg',
    AssetName.menufour:'assets/icons/menu-four-svgrepo-com.svg',
    AssetName.notification:'assets/icons/notification-svgrepo-com.svg',
    AssetName.photo:'assets/icons/photo-svgrepo-com.svg',
    AssetName.photoset:'assets/icons/photoset-svgrepo-com.svg',
    AssetName.pin:'assets/icons/pin-svgrepo-com.svg',
    AssetName.placemarker:'assets/icons/place-marker-svgrepo-com.svg',
    AssetName.powersymbol:'assets/icons/power-symbol-svgrepo-com.svg',
    AssetName.profile1:'assets/icons/profile.svg',
    AssetName.puzzlepiece:'assets/icons/puzzle-piece-svgrepo-com.svg',
    AssetName.rain:'assets/icons/rain-svgrepo-com.svg',
    AssetName.robot:'assets/icons/robot-svgrepo-com.svg',
    AssetName.save:'assets/icons/save-svgrepo-com.svg',
    AssetName.search1:'assets/icons/search.svg',
    AssetName.skull:'assets/icons/skull-svgrepo-com.svg',
    AssetName.snowflake:'assets/icons/snowflake-svgrepo-com.svg',
    AssetName.spark:'assets/icons/spade-svgrepo-com.svg',
    AssetName.spark:'assets/icons/spark-svgrepo-com.svg',
    AssetName.squarebubbleheart:'assets/icons/square-bubble-heart-svgrepo-com.svg',
    AssetName.squarechat:'assets/icons/square-chat-svgrepo-com.svg',
    AssetName.squarelock:'assets/icons/square-lock-svgrepo-com.svg',
    AssetName.tag:'assets/icons/tag-svgrepo-com.svg',
    AssetName.tape1:'assets/icons/tape.svg',
    AssetName.thumbdown:'assets/icons/thumbdown-svgrepo-com.svg',
    AssetName.thumbup:'assets/icons/thumbup-svgrepo-com.svg',
    AssetName.thunderstorm:'assets/icons/thunderstorm-svgrepo-com.svg',
    AssetName.video:'assets/icons/video-svgrepo-com.svg',
    AssetName.camera:'assets/icons/camera-svgrepo-com.svg'
  };
}

enum AssetName {
  search,
  vectorBottom,
  vectorTop,
  headphone,
  tape,
  vectorSmallBottom,
  vectorSmallTop,
  back,
  heart,
  chart,
  discover,
  profile,
  aceOfSpades,
  aceofspadessvgrepocom,
  archerytargetsvgrepocom,
  audio,
  baseball,
  back1,
  baseball1,
  basketball,
  bell,
  birthdaycupcake,
  bitcoin,
  chart1,
  chessknight,
  clap,
  circledcheck,
  codefile,
  diamond,
  dice,
  discover1,
  dribbble,
  electricguitar,
  exit,
  experiment,
  filetext,
  gamepad,
  gear,
  ghost,
  headphone1,
  heart1,
  video,
  thunderstorm,
  thumbup,
  thumbdown,
  tape1,
  tag,
  squarelock,
  squarechat,
  squarebubbleheart,
  spark,
  snowflake,
  skull,
  search1,
  save,
  robot,
  rain,
  puzzlepiece,
  profile1,
  powersymbol,
  placemarker,
  pin,
  photoset,
  photo,
  notification,
  menufour,
  house, camera
}
